-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categories
(
    category_id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id),
    CONSTRAINT category_unique_name UNIQUE (name)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id uuid NOT NULL,
    product_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    bar_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    price integer,
    quantity integer NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    category_id uuid,
    CONSTRAINT products_pkey PRIMARY KEY (product_id),
    CONSTRAINT products_bar_code_key UNIQUE (bar_code),
    CONSTRAINT products_product_name_key UNIQUE (product_name)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id uuid NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id),
    CONSTRAINT roles_name_key UNIQUE (name)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid NOT NULL,
    username character varying(30) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(64) COLLATE pg_catalog."default",
    role_id uuid NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_username_key UNIQUE (username)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
